#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = Thematic
APP_NAME = Thematic
Thematic_APPLICATION_ICON = Thematic.png


#
# Resource files
#
Thematic_RESOURCE_FILES = \
Resources/Thematic.gorm \
Resources/ThemeInspector.gorm \
Resources/ColorElement.gorm \
Resources/ThemeDocument.gorm \
Resources/ImageElement.gorm \
Resources/WindowsElement.gorm \
Resources/MenusElement.gorm \
Resources/MiscElement.gorm \
Resources/TiledElement.gorm \
Resources/Thematic.png \
Resources/ThematicHelp.rtfd 


#
# Header files
#
Thematic_HEADER_FILES = \
AppController.h \
ThemeDocument.h \
ThemeElement.h \
ColorElement.h \
ImageElement.h \
MenusElement.h \
WindowsElement.h \
MiscElement.h \
TiledElement.h

#
# Class files
#
Thematic_OBJC_FILES = \
AppController.m \
ThemeDocument.m \
ThemeElement.m \
ImageElement.m \
MenusElement.m \
WindowsElement.m \
MiscElement.m \
TiledElement.m

#
# Other sources
#
Thematic_OBJC_FILES += \
main.m \
ColorElement.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
